### PR TITLE
Fix temperature_sensor device revision

### PR DESCRIPTION
**Pull request by lboue**
Fix temperature_sensor device revision to match 1.3 specs

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Looks like there is another file that needs copyright info.

**Comment by lboue** [comment]
> Looks like there is another file that needs copyright info.

Fixed but now there is another error
```
Extension error (autoapi.extension):
Handler <function run_autoapi at 0x7f0d1ee68680> for event 'builder-inited' threw an exception (exception: Relative import with too many levels (1) for module 'temperature_sensor')
```

**Comment by tannewt** [comment]
I think the sensor directory needs an empty `__init__.py` to make the folder a package wrt to imports.

**Comment by tannewt** [comment]
The `measurement` folder needs it too.

**Comment by lboue** [comment]
> The `measurement` folder needs it too.

Thanks for the tip. Fixed.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
